"use client";

import { useState } from "react";
import { z } from "zod";
import { ArrowRight, Check, FilePenLine, Plus, Save, ShieldAlert, CalendarDays } from "lucide-react";
import { Badge, Button, Checkbox, Field, Input, Modal, Select, Skeleton, Switch, Textarea, Tooltip } from "@/components/ui/primitives";

const exampleSchema = z.object({ reason: z.string().trim().min(5, "Add a short reason for the visit, at least 5 characters.").max(180, "Keep the reason under 180 characters."), visitType: z.enum(["follow-up", "consultation", "review"]) });

export function Controls() {
  const [reason, setReason] = useState("");
  const [visitType, setVisitType] = useState("follow-up");
  const [error, setError] = useState<string>();
  const [saveStatus, setSaveStatus] = useState("Preview only · nothing is stored");
  const [checked, setChecked] = useState(true);
  const [reminders, setReminders] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const [amendmentReason, setAmendmentReason] = useState("");
  const [amendStatus, setAmendStatus] = useState("");
  return <div className="controls-grid"><div className="controls-column"><span className="eyebrow">Actions & intent</span><div className="button-row"><Button onClick={() => document.getElementById("example-reason")?.focus()}><Plus />New visit</Button><Button variant="secondary" onClick={() => { setReason("Blood pressure follow-up"); setError(undefined); setSaveStatus("Example filled. Review it before saving."); }}><FilePenLine />Use example</Button><Tooltip content="Unavailable until the encounter has a signed note"><span tabIndex={0} className="inline-flex"><Button disabled>Complete visit</Button></span></Tooltip></div><p className="control-note">One primary action. Supporting actions stay quiet. Disabled controls explain what’s missing.</p><div className="control-divider" /><span className="eyebrow">Status, without decoration</span><div className="button-row" style={{ marginTop: 13 }}><Badge>Checked in</Badge><Badge>Rooming</Badge><Badge>Ready</Badge><Badge tone="accent">In progress</Badge><Badge>Done</Badge></div><div className="button-row"><Badge tone="low">↓ Below range</Badge><Badge tone="high">↑ Above range</Badge><Badge tone="critical">Critical</Badge></div><div className="control-divider" /><span className="eyebrow">Deliberate clinical decisions</span><div className="button-row" style={{ marginTop: 12 }}><Modal open={confirmOpen} onOpenChange={(value) => { setConfirmOpen(value); if (!value) { setConfirmation(""); setAmendmentReason(""); } }} title="Amend a signed note" description="The original note stays in the record. An amendment creates a new version with a documented reason. This preview does not change a clinical record." trigger={<Button variant="secondary"><ShieldAlert />Review amendment</Button>}><div className="review-record"><h3>YILMAZ, Aylin</h3><p>Follow-up note · <span className="mono">Version 1</span> · Signed</p></div><Field label="Reason for the amendment" id="amendment-reason"><Textarea id="amendment-reason" value={amendmentReason} onChange={(event) => setAmendmentReason(event.target.value)} placeholder="Explain what needs to be corrected." maxLength={1000} /></Field><div style={{ marginTop: 16 }}><Field label="Type AMEND to acknowledge" id="amend-confirm"><Input id="amend-confirm" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" /></Field></div><div className="dialog-actions"><Button variant="secondary" onClick={() => setConfirmOpen(false)}>Keep original</Button><Button disabled={confirmation !== "AMEND" || amendmentReason.trim().length < 10} onClick={() => { setConfirmOpen(false); setConfirmation(""); setAmendmentReason(""); setAmendStatus("Confirmation preview complete. No record was changed."); }}>Confirm preview</Button></div></Modal></div><p className="save-status" role="status">{amendStatus || "A documented reason and explicit acknowledgment."}</p></div>
    <div className="controls-column"><span className="eyebrow">Inputs & quiet feedback</span><form noValidate onSubmit={(event) => { event.preventDefault(); const parsed = exampleSchema.safeParse({ reason, visitType }); if (!parsed.success) { setError(parsed.error.issues[0].message); setSaveStatus("The example needs a small correction."); document.getElementById("example-reason")?.focus(); return; } setError(undefined); setSaveStatus("Example validated · preview only"); }}><div className="form-grid"><Field label="Visit type" id="example-visit"><Select id="example-visit" label="Visit type" value={visitType} onValueChange={(value) => { setVisitType(value); setSaveStatus("Unsaved example changes"); }} options={[{ value: "follow-up", label: "Follow-up" }, { value: "consultation", label: "Consultation" }, { value: "review", label: "Annual review" }]} /></Field><Field label="Duration" id="example-duration"><Input id="example-duration" value="20 minutes" className="mono" readOnly /></Field><Field className="field-full" label="Reason for visit" id="example-reason" error={error} hint="A few words help your care team prepare."><Input id="example-reason" placeholder="e.g. Blood pressure follow-up" value={reason} aria-invalid={Boolean(error)} aria-describedby={error ? "example-reason-error" : "example-reason-hint"} onChange={(event) => { setReason(event.target.value); setError(undefined); setSaveStatus("Unsaved example changes"); }} maxLength={180} /></Field></div><div style={{ marginTop: 18 }}><Checkbox id="example-check" checked={checked} onCheckedChange={setChecked}>Include preparation instructions</Checkbox><Switch id="example-reminders" checked={reminders} onCheckedChange={setReminders}>Appointment reminders</Switch></div><div className="form-footer"><span className="save-status" role="status">{saveStatus}</span><Button type="submit" variant="secondary"><Save />Save example</Button></div></form></div>
  </div>;
}

export function FeedbackStates() {
  const [recovered, setRecovered] = useState(false);
  const [emptyResolved, setEmptyResolved] = useState(false);
  return <div className="states-grid"><div className="state-panel"><div className="state-label"><span className="eyebrow">Empty</span><span className="mono">01</span></div>{emptyResolved ? <><CalendarDays className="empty-state-icon" /><h3>Follow-up example added</h3><p><span className="mono">21 Sep, 09:20</span> · Dr. Selin Arslan<br />Preview only. No booking was made.</p><Button variant="ghost" size="small" onClick={() => setEmptyResolved(false)}>Reset empty state</Button></> : <><CalendarDays className="empty-state-icon" /><h3>No upcoming appointments</h3><p>When you’re ready, find a time with your care team.</p><Button variant="secondary" size="small" onClick={() => setEmptyResolved(true)}>Preview next state <ArrowRight /></Button></>}</div><div className="state-panel"><div className="state-label"><span className="eyebrow">Loading</span><span className="mono">02</span></div><div role="status" aria-label="Example of appointments loading"><Skeleton className="skeleton-title" /><Skeleton className="skeleton-line skeleton-short" />{[0, 1, 2].map((row) => <div className="skeleton-row" key={row}><Skeleton /><Skeleton /><Skeleton /></div>)}<span className="sr-only">Loading appointment details.</span></div><p style={{ marginTop: 13, fontSize: 11 }}>The layout stays still while data arrives.</p></div><div className="state-panel"><div className="state-label"><span className="eyebrow">Error & recovery</span><span className="mono">03</span></div>{recovered ? <><h3 className="icon-label"><Check />Recovery state preview</h3><p>The example shows where a confirmed save would appear.</p><Button variant="ghost" size="small" onClick={() => setRecovered(false)}>Reset error state</Button></> : <><div className="error-example"><h3>Your note couldn’t be saved.</h3><p>Keep this page open. Check your connection, then try again.</p></div><Button variant="secondary" size="small" onClick={() => setRecovered(true)}>Preview recovery</Button></>}</div></div>;
}
